### ISSUE TITLE
Migrate cudaCreateChannelDesc with less than four channels 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1529]
Quite a few CUDA samples call the function "cudaCreateChannelDesc()" for a single channel. This is not supported by DPCT. Do you have some suggestions on the migration ?  Thanks.

#1108

**Comment by tangjj11** [comment]
Hi, @jinz2014. Good suggestion!
Now, we cannot migrate `cudaCreateChannelDesc()` for a single channel because `sycl::image` only supports 4-channel image format.
But when I support Texture API migration to [bindless image](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc) (Still work in progress, the first PR is [#1345](https://github.com/oneapi-src/SYCLomatic/pull/1345)), it will be supported.

**Comment by tomflinda** [comment]
@jinz2014 https://github.com/oneapi-src/SYCLomatic/pull/1345 has been merged,  Texture API migration has been supported.

**Comment by jinz2014** [comment]
Thanks.
