### ISSUE TITLE
DPCT1098 for store operations ?

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1980]
I think the description in DPCT1098 may be confusing for the store operations:
__stcg

__stcs

__stwb

__stwt

Thanks for your clarification.

**Comment by tomflinda** [comment]
@jinz2014 
The content of the DPCT1098 msg is `The <expression text> expression is used instead of the <function name> call. These two expressions do not provide the exact same functionality. Check the generated code for potential precision and/or performance issues.` 
For more details, pls refer to https://www.intel.com/content/www/us/en/docs/dpcpp-compatibility-tool/developer-guide-reference/2024-1/dpct1098.html.

So, I'm not sure which part of the message is confusing. Could you provide more information?

**Comment by jinz2014** [comment]
For the load operations, the link indicates that we may change the codes generated by SYClomatic. For the store operations, we don't need to make further changes. Is that right ?

**Comment by tomflinda** [comment]
@jinz2014 The current migration mapping has the same semantics as the CUDA side. While the implementation of the CUDA side leverages cache operations, it has performance advantages; the SYCL side may not use cache operations.
