### ISSUE TITLE
The size of sycl::float3 is 12 bytes

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#340]
The size of float3 in Cuda is 12 bytes, but the size of sycl::float3 is 16 bytes.

**Comment by tomflinda** [comment]
Hi @zjin-lcf , according to sycl2020 spec 4.14.2.6. Memory layout and alignment, it is a expect behavior that  sycl::float3 is 16 bytes (.i.e.: sizeof(float) * 4).
So there is a gap between CUDA and SYCL.
We are considering to emit a warning msg when migrating pattern like "sizeof(float3)" to indicate users that there is a language gap here, he/she may need to adjust their code.
Thanks.

**Comment by zjin-lcf** [comment]
More data will need to be moved between a host and a device when float3 takes 16 bytes. Please let the SYCL committee know. Thanks.

**Comment by keryell** [comment]
This one is a tough one because SYCL follows how C++ works.
Same for `sycl::marray` and `sycl::mfloat3`.
Can someone try `__attribute__ ((aligned))` https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes on a `typedef` to the SYCL type if I understand correctly a way to decrease the alignment to 3:
> When used on a struct, or struct member, the aligned attribute can only increase the alignment; in order to decrease it, the packed attribute must be specified as well. When used as part of a typedef, the aligned attribute can both increase and decrease alignment, and specifying the packed attribute generates a warning.

**Comment by keryell** [comment]
@zjin-lcf  @tomflinda Good news, by discussing with @Ralender I realized I was completely wrong about how C++ works. :-)
`sycl::vec` have the exception for the size of 3 https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#memory-layout-and-alignment but the `sycl::marray` are fine because of https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#memory-layout-and-alignment

An equivalent demo: https://godbolt.org/z/4fK9GxEM6
So, if SYCLomatic uses `sycl::marray` instead of `sycl::vec` it should just-work™.

**Comment by tomflinda** [comment]
@keryell thanks for your information,  while for cuda cuRAND APIs https://docs.nvidia.com/cuda/curand/group__DEVICE.html, the type of return value is cuda::vec, and the mapping part in oneMKL https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/random-number-generators/random-number-generators-device-routines/device-generate-routines/oneapi-mkl-rng-device-generate.html, its type of return value is sycl::vec, and there is no implicit type cast in SYCL2020. That's the reason why we use sycl::vec to map cuda::vec currently.

**Comment by keryell** [comment]
@tomflinda It might be complex to migrate CUDA code using arrays of small vectors of size 3 if using `sycl::vec` instead of `sycl::marray`.
But looking at the `cudarand` link you give, it looks like there are only vectors of size 2 and 4, so there is not such an issue for now?

**Comment by tomflinda** [comment]
@keryell 
1. for the gap that size of float3 in cuda is 12 bytes while in sycl it is 16 bytes, we are considering to emit a warning msg in the migrated code to remind user to adjust the migrated code.
2. yes, for vectors of size 2 and 4, there is no this kind of issue.

**Comment by keryell** [comment]
A transition phase could be to update your library with an API & ABI break to use only `sycl::marray` and to add to SYCL an implicit conversion from `sycl::marray` to `sycl::vec`.

**Comment by tomflinda** [comment]
@keryell yes, that's a solution, we will do a further investigation to decide whether to migrate cuda vec to sycl::marray. thanks.

**Comment by tomflinda** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/467 is implemented to emit a warning msg when migrating pattern like "sizeof(float3)" to indicate users that there is a language gap here, he/she may need to adjust their code.

**Comment by tomflinda** [comment]
Currently, we have no plan to migrate cuda vec to sycl::marray.
