### ISSUE TITLE
migrate the divide intrinsic instruction

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#410]
__fdividef(x,y) may be converted to a fast divide in SYCL instead of `x/y`.

**Comment by tomflinda** [comment]
@zjin-lcf the reason why we migrate __fdividef(x,y) to x/y instead of sycl::native::divide(x, y) is that x/y has higher precision than sycl::native::divide(x, y) defined in SYCL2020 spec on opencl cpu backend. we will follow this issue with dpcpp compiler team, when the precision issue is fixed in sycl::native::divide(x,y), we will update the migration rule.  thanks.

**Comment by zhiweij1** [comment]
Hi @zjin-lcf , the sycl compiler team does not think the precision loss on CPU backend is an issue. So, we will keep this migration.

**Comment by zjin-lcf** [comment]
Regardless of the precision, what is the expected SYCL function for the instrinisic function ? Thanks.

**Comment by zhiweij1** [comment]
Hi @zjin-lcf , if we do not consider precision, the mapping for CUDA intrinsic functions should be sycl::native functions (if available).
