### ISSUE TITLE
DPCT1007:2: Migration of atomicDec is not supported

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#559]
DPCT1007:2: Migration of atomicDec is not supported. However,  atomicInc() can be migrated. 

I posted a feature request (https://github.com/intel/llvm/issues/8220).

Could you please explain that the implementation of atomicDec() below does not work ? Thanks.

```
        // atomicDec(&gpuData[8], 137)

        auto ao8 = atomic_ref<T, memory_order::relaxed, memory_scope::device,
                              access::address_space::global_space>(gpuData[8]);
        while (true) {
          T old = ao8.load();
          if (old == 0 || old > 137) {
            if (ao8.compare_exchange_strong(old, 137)) break;
          } else if (ao8.compare_exchange_strong(old, old - 1)) break;
        }
```

**Comment by tomflinda** [comment]
@zjin-lcf Could you provide a complete executable reproducer?

**Comment by zjin-lcf** [comment]
Please see the example

```
__global__ void f (unsigned int *d) {
   atomicDec(d, 137);
}
```

**Comment by tomflinda** [comment]
@zjin-lcf the example you provided is just a device function, I want you to provide a complete executable reproducer, so that I can reproduce the issue you reported,
Or pls try the WA to migrate example your provided
```
__global__ void f (unsigned int *d) {
   atomicDec(d, 137);
}
```
with:
```
template <sycl::access::address_space addressSpace = sycl::access::address_space::global_space,
          sycl::memory_order memoryOrder = sycl::memory_order::relaxed,
          sycl::memory_scope memoryScope = sycl::memory_scope::device>
inline unsigned int atomic_fetch_compare_dec(unsigned int *addr,
                                             unsigned int operand) {
  auto atm = sycl::atomic_ref<unsigned int, memoryOrder, memoryScope,
                                  addressSpace>(addr[0]);
  unsigned int old;
 
	while (true) {
	  old = atm.load();
	  if (old == 0 || old > operand) {
		if (atm.compare_exchange_strong(old, operand)) break;
	  } else if (atm.compare_exchange_strong(old, old - 1)) break;
	}  
  
  return old;
}

void f (unsigned int *d) {
    atomic_fetch_compare_dec<sycl::access::address_space::generic_space>(d, 137);
}

```

**Comment by zjin-lcf** [comment]
Sorry. Please see the example in CUDA: https://github.com/zjin-lcf/HeCBench/tree/master/atomicIntrinsics-cuda.  It was updated with the addition of atomicInc and atomicDec yesterday.

The SYCL "atomicDec" function hangs, but the SYCL "atomicInc" function works. 

Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf the possible root cause is that the work-group size passed to the SYCL kernel may exceed the HW
    limit. 

You can try it to do the following changes:
```
diff --git a/atomicIntrinsics-cuda/main.cu b/atomicIntrinsics-cuda/main.cu
index e72cc587..d433e0d4 100644
--- a/atomicIntrinsics-cuda/main.cu
+++ b/atomicIntrinsics-cuda/main.cu
@@ -26,8 +26,8 @@
 template <class T>
 void testcase(const int repeat)
 {
-  unsigned int len = 1 << 27;
-  unsigned int numThreads = 256;
+  unsigned int len = 256;
+  unsigned int numThreads = 16;
   unsigned int numBlocks = (len + numThreads - 1) / numThreads;
   T gpuData[] = {0, 0, (T)-256, 256, 255, 0, 255, 0, 0};
   unsigned int memSize = sizeof(gpuData);

```

Then do the migration and apply the WA for "atomicDec((unsigned int *)&g_odata[8], 137)" in the migrated code kernel.h:
```
template <sycl::access::address_space addressSpace = sycl::access::address_space::global_space,
          sycl::memory_order memoryOrder = sycl::memory_order::relaxed,
          sycl::memory_scope memoryScope = sycl::memory_scope::device>
inline unsigned int atomic_fetch_compare_dec(unsigned int *addr,
                                             unsigned int operand) {
  auto atm = sycl::atomic_ref<unsigned int, memoryOrder, memoryScope,
                                  addressSpace>(addr[0]);
  unsigned int old;
 
	while (true) {
	  old = atm.load();
	  if (old == 0 || old > operand) {
		if (atm.compare_exchange_strong(old, operand)) break;
	  } else if (atm.compare_exchange_strong(old, old - 1)) break;
	}  
  
  return old;
}

template <class T>
void testKernel(T *g_odata, sycl::nd_item<3> item_ct1)
{
   .....
    // Atomic decrement
    /*
    DPCT1007:2: Migration of atomicDec is not supported.
    */
    //atomicDec((unsigned int *)&g_odata[8], 137);
	
    atomic_fetch_compare_dec<sycl::access::address_space::generic_space>(
        (unsigned int *)&g_odata[8], (unsigned int)137);
}
```
Then the test case should pass.

**Comment by zjin-lcf** [comment]
Thank you for the answer. I am confused that the Cuda program passes the test and the length and work-group size need the proposed changes in Sycl program. Both programs run on an Nvidia GPU. Could you please explain the hardware limit ?

**Comment by tomflinda** [comment]
@zjin-lcf it seems a bug of SYCL runtime, we will report this issue to SYCL compiler team.

**Comment by zjin-lcf** [comment]
Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf  https://github.com/oneapi-src/SYCLomatic/pull/595 has implemented the migration of `atomicDec`, for the root cause that why migrated SYCL code without changing `the length and work-group size` hangs on Nvidia GPU, I have reported it to SYCL compiler team, and waiting for their feedback.

**Comment by zjin-lcf** [comment]
Thank you. I look forward to understanding the root cause.

**Comment by jinz2014** [comment]
Do you have feedback from the SYCL compiler team ?

**Comment by zjin-lcf** [comment]
Do you have feedback from the compiler team ?

**Comment by tomflinda** [comment]
@zjin-lcf  the latest feedback said that the issue is under investigation, since this issue is not related to SYComatic, I have closed it.

**Comment by GeorgeWeb** [comment]
Hi @zjin-lcf :wave: Apologies for getting on this issue very late, I hope you haven't been too inconvenienced with the slower performance of the branched atomicCAS loop workaround in place. 

We are working on possible cuda-backend builtin that may be manually utilised in `SYCLomatic` for `NVPTX` sycl targets but in the meantime we have a workaround you can use to map to the correct cuda builtin and no extra overhead, just yielding the right builtin for atomic fetch compare inc/dec. See following commit in my fork of SYCLomatic: [SYCLomatic/commit/cdf13dd](https://github.com/GeorgeWeb/SYCLomatic/commit/cdf13dd7cf41a32992693a7ede461f8203d24184).

The PTX of the kernel removes the branching from the previous WA and replaces the said CAS loop with the inc/dec builtins:
```c
add.s64 %rd9, %rd2, 28;
atom.inc.u32 %r16, [%rd9], 17;
add.s64 %rd10, %rd2, 32;
atom.dec.u32 %r17, [%rd10], 137;
```
These are for the generic address space but the intrinsics for global and local sycl address spaces are also available.

Once we see if the mentioned new builtin(s) (e.g. `__libclc_cuda_atomic_cmp_inc(unsigned *, unsigned);`) could fit the way things work in our handling of builtins through `libclc` (specializing the implementation of spirv symbols), we may then have a DPC++ patch for those atomics which can then be used more generally. In more details, this is basically a bit of a special-case because we cannot reuse the existing spirv symbols (which is what libclc implements), because the CUDA functions for `atomicInc/Dec` have an extra parameter for the comparison operation and that would require extending SPIR-V and rationalizing this extension which may really not go anywhere in the end as not many HWs support these particular instructions the way Nvidia does. Therefore, we're looking for a way to special-case emitting the new `libclc` builtin only for Cuda compilation, and see how that goes. Thank you and appreciate your patience!

**Comment by zjin-lcf** [comment]
HI @GeorgeWeb 

I will be patient. Thank you for describing the migration in details.
